services:
  front:
    build: .
    image: nextjs-practice-front
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules


# 参考URL
# https://zenn.dev/yuki_tu/articles/01c7963eeb2876
# https://zenn.dev/temple_c_tech/articles/setup-next-on-docker
