import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Logo } from '@/components/Logo'
import { Links } from '@/components/Links'
import { MainImage } from '@/components/MainImage'
import { Path } from '@/components/Path'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <Path page="about"/>
          <Logo />
        </div>
        <MainImage />
        <Links />
      </main>
    </>
  )
}
